### ISSUE TITLE
BCAT to include - news

### ISSUE THREAD

**Issue by PatrickD1985** [Random0666/BCAT-Manager#1]
Hi there,

As briefly discussed on Twitter, IIRC BCAT is also the server/service that is tasked with supplying content to the Nintendo Switch NEWS channel. 
Or at least according to https://switchbrew.org/wiki/Network#Servers_3 
Is this something that should fit in your tool or possible?

Either way thanks once again for your reply, time and effort.

Kind regards!

**Comment by Random06457** [comment]
Hi the tool now supports News data!

**Comment by PatrickD1985** [comment]
Awesome, going to look into it later today :) 
Very cool that you looked into this!

**Comment by PatrickD1985** [comment]
Cool retrieving works wonderful I really love the work you put in to this!
Wondering one thing though, the files that get stored for news, how would I go about opening those?

**Comment by Random06457** [comment]
Sorry I didn't see you comment earlier.
So I'm still working on the News viewer control if it's what you're talking about and I'll update the repo as soon as I'm done with it.
It currently looks like : 

![](https://cdn.discordapp.com/attachments/432400335235973120/515914140854911001/20181124_163557.jpg)
![](https://cdn.discordapp.com/attachments/432400335235973120/515914141328736297/20181124_163644.jpg)

**Comment by PatrickD1985** [comment]
Yep it was. Because I just couldn't make out how to get the content of the item. But ok its WIP. No harm still awesome work I must say. Much appreciated!
